# ===========================================================================================
# IOT Server Address
# 	IOT_API_SERVER_ADDRESS string
# ===========================================================================================

iot:
  api:
    url:

# ===========================================================================================
# Database Address
# ===========================================================================================

database:
  name: mysql
  version: 5.7.16
  dsn:


# ===========================================================================================
# Blockchain Server Address
#   var ccName string = "app_container_cc"
#   var peerAddress string = "http://127.0.0.1:7050"
# ===========================================================================================

fabric:
  version: v0.6.1-preview
  peer:
    address: http://127.0.0.1:7050
  chaincode:
    name:



# ===========================================================================================
# Local Server Address
#   	SERVER_ADDRESS string = "0.0.0.0:9090"
#       MAX_CONNECTION_LIMIT int = 100
# ===========================================================================================
local:
  server:
    version: 0.6.0
    address: 0.0.0.0:9090
    max_connection_limit: 100
    session:
      duration: 48h